### ISSUE TITLE
A seperate PDF for the old exams

### ISSUE THREAD

**Issue by Boutry** [vhuber/ensiie#1]
So far we only have the exam of 2009/2010 but more could be added.

**Comment by vhuber** [comment]
Chapter 6 I guess @Boutry  ?

**Comment by Boutry** [comment]
No it corresponds to section 4.6.

**Comment by vhuber** [comment]
Do you want it to be removed from the `make cours` ?

**Comment by Boutry** [comment]
Just as for the issue about the projects something like "make exams" would be nice.
