### ISSUE TITLE
A seperate PDF for the projects

### ISSUE THREAD

**Issue by Boutry** [vhuber/ensiie#2]

**Comment by vhuber** [comment]
chapter 6 I guess ? @Boutry

**Comment by Boutry** [comment]
Yes.

**Comment by vhuber** [comment]
`make chap`will generate chap6.pdf.
Is that file OK for you ?

**Comment by Boutry** [comment]
The thing is that I don't consider projects as being part of the course. I corresponds to a different course. Something like "make projets" would make more sense.
